# setup.py
# This file is generated by Shroud 0.12.2. Do not edit.
from setuptools import setup, Extension

module = Extension(
    'abispack',
    sources=[
         'abispack/pyabispack_Libabigailtype.cpp',
         'abispack/pyabispack_abispackmodule.cpp',
         'abispack/pyabispackmodule.cpp',
         'abispack/pyabispackutil.cpp'
    ],
    language='c++',
    include_dirs = None,
#    libraries = ['tcl83'],
#    library_dirs = ['/usr/local/lib'],      
#    extra_compile_args = [ '-O0', '-g' ],
#    extra_link_args =
)

setup(
    name='abispack',
    ext_modules = [module],
)
