// pyabispackmodule.hpp
// This file is generated by Shroud 0.12.2. Do not edit.
#ifndef PYABISPACKMODULE_HPP
#define PYABISPACKMODULE_HPP

#include <Python.h>

// cxx_header
#include "../include/abispack.hpp"

// splicer begin header.include
// splicer end header.include

// utility functions
extern void PY_SHROUD_release_memory(int icontext, void *ptr);
extern void *PY_SHROUD_fetch_context(int icontext);
extern void PY_SHROUD_capsule_destructor(PyObject *cap);

// ------------------------------
extern PyTypeObject PY_Libabigail_Type;
// splicer begin namespace.abispack.class.Libabigail.C_declaration
// splicer end namespace.abispack.class.Libabigail.C_declaration

typedef struct {
PyObject_HEAD
    abispack::Libabigail * obj;
    int idtor;
    // splicer begin namespace.abispack.class.Libabigail.C_object
    // splicer end namespace.abispack.class.Libabigail.C_object
} PY_Libabigail;

extern const char *PY_Libabigail_capsule_name;
PyObject *PP_Libabigail_to_Object_idtor(abispack::Libabigail *addr,
    int idtor);
PyObject *PP_Libabigail_to_Object(abispack::Libabigail *addr);
int PP_Libabigail_from_Object(PyObject *obj, void **addr);
// ------------------------------

// splicer begin header.C_declaration
// splicer end header.C_declaration

extern PyObject *PY_error_obj;

#if PY_MAJOR_VERSION >= 3
extern "C" PyMODINIT_FUNC PyInit_abispack(void);
#else
extern "C" PyMODINIT_FUNC initabispack(void);
#endif

#endif  /* PYABISPACKMODULE_HPP */
